-- 주문 RAW 테이블 (자사몰 주문 내보내기 · 상품 라인 단위) · 대시보드 "＋ 주문 RAW" 버튼이 upsert
-- 실행: Supabase Dashboard > SQL Editor 에 붙여넣고 Run (여러 번 실행해도 안전)

create table if not exists public.b2c_order_raw (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.b2c_order_raw
  add column if not exists line_key              text,            -- 주문번호|상품명|순번 (upsert 키)
  add column if not exists order_no              text,            -- 주문번호
  add column if not exists order_date            date,            -- 주문일 (주문번호 앞 8자리)
  add column if not exists member_id             text,            -- 주문자ID
  add column if not exists buyer_name            text,            -- 주문자명
  add column if not exists product_name          text,            -- 상품명
  add column if not exists quantity              integer,         -- 수량
  add column if not exists pay_total             numeric(14,0),   -- 총 결제금액(KRW)
  add column if not exists pay_actual            numeric(14,0),   -- 총 실결제금액(최초정보)(KRW)
  add column if not exists product_amount        numeric(14,0),   -- 상품구매금액(KRW)
  add column if not exists channel_order_no      text,            -- 주문경로 주문번호(마켓/네이버페이)
  add column if not exists channel_item_order_no text,            -- 주문경로 품목별 주문번호
  add column if not exists flag                  text,            -- '' 정상 · 'x' 취소 추정(결제 0, 최초 실결제>0) · 't' 테스트계정
  add column if not exists source_file           text,            -- 업로드 파일명
  add column if not exists imported_at           timestamptz not null default now();

create unique index if not exists b2c_order_raw_line_key_key   on public.b2c_order_raw (line_key);
create index        if not exists b2c_order_raw_order_no_idx   on public.b2c_order_raw (order_no);
create index        if not exists b2c_order_raw_order_date_idx on public.b2c_order_raw (order_date);
create index        if not exists b2c_order_raw_member_id_idx  on public.b2c_order_raw (member_id);

-- 개인정보(주문자명·ID) 포함: RLS 켜고 공개 읽기 정책은 만들지 않음
alter table public.b2c_order_raw enable row level security;
