-- 회원 RAW 테이블 (자사몰 회원 내보내기 CSV 업로드용)
-- 실행: Supabase Dashboard > SQL Editor 에 붙여넣고 Run
-- 업로드: Table Editor > b2c_member_raw > Import data from CSV > uploads/b2c_member_raw_YYYYMMDD.csv (영문 헤더 변환본)

-- 테이블이 없으면 생성, 이미 있으면(Table Editor 에서 만든 경우) 컬럼만 추가
create table if not exists public.b2c_member_raw (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.b2c_member_raw
  add column if not exists member_id         text,                     -- 아이디
  add column if not exists name              text,                     -- 이름
  add column if not exists grade             text,                     -- 회원등급
  add column if not exists age               smallint,                 -- 나이
  add column if not exists email             text,                     -- 이메일
  add column if not exists phone             text,                     -- 휴대폰번호
  add column if not exists points_used       numeric(12,2) default 0,  -- 총 사용 적립금
  add column if not exists points_available  numeric(12,2) default 0,  -- 사용가능 적립금
  add column if not exists joined_at         date,                     -- 회원 가입일
  add column if not exists dormant_at        date,                     -- 휴면처리일
  add column if not exists withdrawn_at      date,                     -- 탈퇴일
  add column if not exists withdrawal_type   text,                     -- 탈퇴구분
  add column if not exists withdrawal_reason text,                     -- 탈퇴사유
  add column if not exists imported_at       timestamptz not null default now();

create unique index if not exists b2c_member_raw_member_id_key on public.b2c_member_raw (member_id);

comment on table  public.b2c_member_raw is '자사몰 회원 RAW (CSV 업로드 원본)';
comment on column public.b2c_member_raw.member_id         is '아이디';
comment on column public.b2c_member_raw.name              is '이름';
comment on column public.b2c_member_raw.grade             is '회원등급';
comment on column public.b2c_member_raw.age               is '나이';
comment on column public.b2c_member_raw.email             is '이메일';
comment on column public.b2c_member_raw.phone             is '휴대폰번호';
comment on column public.b2c_member_raw.points_used       is '총 사용 적립금';
comment on column public.b2c_member_raw.points_available  is '사용가능 적립금';
comment on column public.b2c_member_raw.joined_at         is '회원 가입일';
comment on column public.b2c_member_raw.dormant_at        is '휴면처리일';
comment on column public.b2c_member_raw.withdrawn_at      is '탈퇴일';
comment on column public.b2c_member_raw.withdrawal_type   is '탈퇴구분';
comment on column public.b2c_member_raw.withdrawal_reason is '탈퇴사유';

create index if not exists b2c_member_raw_joined_at_idx on public.b2c_member_raw (joined_at);
create index if not exists b2c_member_raw_email_idx     on public.b2c_member_raw (email);

-- 개인정보(이름·이메일·휴대폰) 포함: RLS 켜고 공개 읽기 정책은 만들지 않음 (service_role 전용)
alter table public.b2c_member_raw enable row level security;

-- 재업로드 전 초기화가 필요할 때만 실행
-- truncate table public.b2c_member_raw;
